// This is a simplified example config file for quickstart
// Some not frequently used features are omitted/commented out here
// For a full-featured example, please refer to `uptime.config.full.ts`

// Don't edit this line
import { MaintenanceConfig, PageConfig, WorkerConfig } from './types/config'

const pageConfig: PageConfig = {
  // Title for your status page
  title: "BBY's Status Page",
  // Links shown at the header of your status page
  links: [
    { link: 'https://github.com/lyc8503', label: 'GitHub' },
  ],
}

const workerConfig: WorkerConfig = {
  monitors: [
    // === 你原有的监控项 ===
    {
      id: 'random_url',
      name: '随机访问网址',
      method: 'GET',
      target: 'http://arcticocean.cc.cd/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'mizuki_e',
      name: 'Mizuki (e)',
      method: 'GET',
      target: 'http://e.m.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'mizuki_v',
      name: 'Mizuki (v)',
      method: 'GET',
      target: 'https://v.m.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'mizuki_m',
      name: 'Mizuki (m)',
      method: 'GET',
      target: 'https://m.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'firefly_e',
      name: 'FireFly (e)',
      method: 'GET',
      target: 'http://e.f.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'bing_wallpaper',
      name: 'bing-wallpaper',
      method: 'GET',
      target: 'https://bing-wallpaper.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'home_page',
      name: 'Home_Page',
      method: 'GET',
      target: 'http://home_page.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'short_link',
      name: '短链',
      method: 'GET',
      target: 'http://xn--37qy7as38c.cc.cd/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'music',
      name: 'Music',
      method: 'GET',
      target: 'https://music.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'blog_cc',
      name: 'BLOG',
      method: 'GET',
      target: 'https://博客.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'waline',
      name: '评论',
      method: 'GET',
      target: 'https://waline.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'firefly_v',
      name: 'FireFly (v)',
      method: 'GET',
      target: 'https://v.f.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'blog_f',
      name: 'Blog (f)',
      method: 'GET',
      target: 'https://f.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'digital_garden',
      name: '数字花园',
      method: 'GET',
      target: 'https://suanyyds.fast-page.org/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'cloudflare_mail',
      name: 'cloudflare-mail',
      method: 'GET',
      target: 'https://cloudflaretempemail.pages.dev/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'cloud_mail',
      name: 'cloud-mail',
      method: 'GET',
      target: 'https://cloud.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'moemail',
      name: 'moemail',
      method: 'GET',
      target: 'http://moemail.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'k_vault',
      name: 'k-vault',
      method: 'GET',
      target: 'https://k-vault.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'astro',
      name: 'Astro',
      method: 'GET',
      target: 'https://astro.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'durable_chat',
      name: 'chat',
      method: 'GET',
      target: 'https://durable-chat-template.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'liaotian',
      name: '聊天',
      method: 'GET',
      target: 'https://liaotian.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'git_cc',
      name: 'GITHUB',
      method: 'GET',
      target: 'https://git.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'github_cc',
      name: 'github',
      method: 'GET',
      target: 'https://github.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'substracker',
      name: '订阅管理系统',
      method: 'GET',
      target: 'https://substracker.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'tg_netdisk',
      name: 'TG网盘',
      method: 'GET',
      target: 'https://loveyou.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'sanyue_netdisk',
      name: 'Sanyue网盘',
      method: 'GET',
      target: 'https://beibinyang.pages.dev/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'cesu',
      name: '测速',
      method: 'GET',
      target: 'https://cesu.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'hide',
      name: '隐藏图片和文档',
      method: 'GET',
      target: 'https://hide.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'wordpress',
      name: 'WordPress',
      method: 'GET',
      target: 'https://xinyuan1.dpdns.org/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'blog_o',
      name: '博客 (o)',
      method: 'GET',
      target: 'https://o.ovo.tw.kg/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'gift',
      name: 'gift',
      method: 'GET',
      target: 'http://gift.loveslife.biz/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'chat_mydiscussion',
      name: 'Chat (mydiscussion)',
      method: 'GET',
      target: 'http://chat.mydiscussion.net/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'bby_homepage',
      name: 'bby-个人主页',
      method: 'GET',
      target: 'https://a.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'bby_bookmark',
      name: '书签',
      method: 'GET',
      target: 'https://bby.free.nf/xiaoshuqian',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'bby_wp',
      name: 'wp',
      method: 'GET',
      target: 'https://bby.free.nf/wangpan/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'tuchuang',
      name: '图床',
      method: 'GET',
      target: 'http://tu.66ghz.com/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'suan',
      name: 'suan',
      method: 'GET',
      target: 'https://sl28592369-4.jzfkw.net/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'pan_2024',
      name: 'Pan (2024)',
      method: 'GET',
      target: 'https://2024.66ghz.com/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },

    // === 从“数字花园”链接收藏页提取的新监控项 ===
    // 注意：一些项目（如“待修复”）可能无法访问，建议先添加观察
    {
      id: 'hugo_site',
      name: 'Hugo',
      method: 'GET',
      target: 'https://你的hugo站点地址/', // ⚠️ 请替换为从页面获取的实际链接
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'mizuki_edgeone',
      name: 'Mizuki (EdgeOne)',
      method: 'GET',
      target: 'https://mizuki-lun3iaoh.edgeone.dev/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'mizuki_vercel',
      name: 'Mizuki (Vercel)',
      method: 'GET',
      target: 'https://mizuki-lemon.vercel.app/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'firefly_edgeone',
      name: 'FireFly (EdgeOne)',
      method: 'GET',
      target: 'https://firefly1.edgeone.dev/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'cloudpaste',
      name: 'CloudPaste',
      method: 'GET',
      target: 'https://cloudpaste.cccccccc.qzz.io/', // 根据域名模式推测
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'cf_mail_alt',
      name: 'cloudflare-mail (备用)',
      method: 'GET',
      target: 'https://cf-mail.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'sky_mail',
      name: 'cloud-mail (sky)',
      method: 'GET',
      target: 'https://sky.cccccccc.qzz.io',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'moemail_pages',
      name: 'moemail (pages)',
      method: 'GET',
      target: 'https://moemail-dar.pages.dev/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'k_vault_pages',
      name: 'k-vault (pages)',
      method: 'GET',
      target: 'https://k-vault-23t.pages.dev/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'blog_notion',
      name: 'Blog (Notion)',
      method: 'GET',
      target: 'https://notion-next-drab-five-53.vercel.app/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'blog_http',
      name: '博客 (HTTP)',
      method: 'GET',
      target: 'http://blog.cccccccc.qzz.io/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'bby_blog_love',
      name: 'Blog (love)',
      method: 'GET',
      target: 'https://bby.lovestoblog.com/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'beizi_blog',
      name: 'blog (beizi)',
      method: 'GET',
      target: 'https://beizi.lovestoblog.com/',
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'bbt_forum',
      name: 'bbt (Flarum)',
      method: 'GET',
      target: 'https://bbt.freeflarum.com/', // ⚠️ 请从页面确认完整域名
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    {
      id: 'xinyuan_wish',
      name: '昕渊',
      method: 'GET',
      target: 'https://xinyuan1.dpdns.org/', // 与原有 wordpress 可能重复，但保留
      timeout: 10000,
      expectedCodes: [200, 302, 301],
    },
    // 注：部分标记为“待修复”或状态不明的链接未添加，你可以后续根据情况手动补充
  ],

  notification: {
    webhook: {
      url: 'https://oapi.dingtalk.com/robot/send?access_token=c1cde81ed481ada8e8c66192d74a85e2cb97ae54b263e2d144e1832b35c66d13',
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      payloadType: 'json',
      payload: {
        msgtype: 'text',
        text: {
          // ✅ 使用修正后的占位符
          content: '🔔 UptimeFlare 监控通知\n📌 监控名称: {name}\n📊 状态: {status}\n🔗 监控地址: {target}\n📝 详情: {message}\n⏰ 时间: {time}'
        },
      },
      timeout: 10000,
    },
    timeZone: 'Asia/Shanghai',
    // ✅ 60秒通知间隔，有效防止消息轰炸
    gracePeriod: 60,
  },
}

// 清空维护窗口
const maintenances: MaintenanceConfig[] = []

// Don't edit this line
export { maintenances, pageConfig, workerConfig }
